include:
  - path: ../backend-ifts/docker-compose.yml

services:
  api:
    environment:
      CORS_ORIGINS: http://localhost

  front:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
    ports:
      - "80:80"
    depends_on:
      - api
