/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/recordatorios/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recordatorios */
        get: operations["get_recordatorios_recordatorios__get"];
        put?: never;
        /** Create Recordatorio */
        post: operations["create_recordatorio_recordatorios__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordatorios/{recordatorio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Recordatorio */
        delete: operations["delete_recordatorio_recordatorios__recordatorio_id__delete"];
        options?: never;
        head?: never;
        /** Update Recordatorio */
        patch: operations["update_recordatorio_recordatorios__recordatorio_id__patch"];
        trace?: never;
    };
    "/materias/carreras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Carreras */
        get: operations["get_carreras_materias_carreras_get"];
        put?: never;
        /** Crear Carrera */
        post: operations["crear_carrera_materias_carreras_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materias/carreras/{carrera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Carrera
         * @description Detalle de una carrera. `404` si no existe. Lectura pública.
         */
        get: operations["get_carrera_materias_carreras__carrera_id__get"];
        /** Actualizar Carrera */
        put: operations["actualizar_carrera_materias_carreras__carrera_id__put"];
        post?: never;
        /** Eliminar Carrera */
        delete: operations["eliminar_carrera_materias_carreras__carrera_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materias/carrera/{carrera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Materias By Carrera */
        get: operations["get_materias_by_carrera_materias_carrera__carrera_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materias/buscar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar Materias */
        get: operations["buscar_materias_materias_buscar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materias/correlativas/{materia_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Correlativas */
        get: operations["get_correlativas_materias_correlativas__materia_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materias/correlativas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear Correlativa */
        post: operations["crear_correlativa_materias_correlativas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materias/correlativas/{correlativa_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Eliminar Correlativa */
        delete: operations["eliminar_correlativa_materias_correlativas__correlativa_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materias/usuario/{usuario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Materias Usuario */
        get: operations["get_materias_usuario_materias_usuario__usuario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materias/promedio/{usuario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Promedio */
        get: operations["get_promedio_materias_promedio__usuario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materias/usuario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Materia Usuario */
        post: operations["add_materia_usuario_materias_usuario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materias/cursada/{materia_usuario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Materia Usuario */
        delete: operations["delete_materia_usuario_materias_cursada__materia_usuario_id__delete"];
        options?: never;
        head?: never;
        /** Update Materia Usuario */
        patch: operations["update_materia_usuario_materias_cursada__materia_usuario_id__patch"];
        trace?: never;
    };
    "/materias/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear Materia */
        post: operations["crear_materia_materias__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materias/{materia_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Materia
         * @description Detalle de una materia. `404` si no existe. Lectura pública.
         */
        get: operations["get_materia_materias__materia_id__get"];
        /** Actualizar Materia */
        put: operations["actualizar_materia_materias__materia_id__put"];
        post?: never;
        /** Eliminar Materia */
        delete: operations["eliminar_materia_materias__materia_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recursos/usuario/{usuario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get By Usuario */
        get: operations["get_by_usuario_recursos_usuario__usuario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recursos/materia/{materia_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get By Materia */
        get: operations["get_by_materia_recursos_materia__materia_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recursos/{recurso_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get By Id */
        get: operations["get_by_id_recursos__recurso_id__get"];
        /** Update */
        put: operations["update_recursos__recurso_id__put"];
        post?: never;
        /** Delete */
        delete: operations["delete_recursos__recurso_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recursos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All */
        get: operations["get_all_recursos__get"];
        put?: never;
        /** Create */
        post: operations["create_recursos__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/convenios/carrera/{carrera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get By Carrera */
        get: operations["get_by_carrera_convenios_carrera__carrera_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/convenios/{convenio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get By Id */
        get: operations["get_by_id_convenios__convenio_id__get"];
        /** Update */
        put: operations["update_convenios__convenio_id__put"];
        post?: never;
        /** Delete */
        delete: operations["delete_convenios__convenio_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/convenios/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All */
        get: operations["get_all_convenios__get"];
        put?: never;
        /** Create */
        post: operations["create_convenios__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/talentotech/carrera/{carrera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get By Carrera */
        get: operations["get_by_carrera_talentotech_carrera__carrera_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/talentotech/categoria/{categoria}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get By Categoria */
        get: operations["get_by_categoria_talentotech_categoria__categoria__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/talentotech/{talentotech_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get By Id */
        get: operations["get_by_id_talentotech__talentotech_id__get"];
        /** Update */
        put: operations["update_talentotech__talentotech_id__put"];
        post?: never;
        /** Delete */
        delete: operations["delete_talentotech__talentotech_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/talentotech/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All */
        get: operations["get_all_talentotech__get"];
        put?: never;
        /** Create */
        post: operations["create_talentotech__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/registro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Registra un nuevo usuario.
         */
        post: operations["register_auth_registro_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Inicia sesión y devuelve un token JWT.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Devuelve los datos del usuario autenticado (protegido).
         */
        get: operations["get_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description Actualiza el nombre y/o apellido del usuario autenticado.
         */
        patch: operations["update_me_auth_me_patch"];
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Token */
        get: operations["verify_token_auth_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Dispara el envío del email de reset. Responde siempre lo mismo,
         *     exista o no el email, para no revelar qué direcciones están registradas.
         */
        post: operations["forgot_password_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Consume el token de un solo uso y actualiza la contraseña.
         */
        post: operations["reset_password_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cambiar Password
         * @description Cambia la contraseña del usuario autenticado. Requiere la actual.
         */
        patch: operations["cambiar_password_auth_password_patch"];
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CambiarPasswordRequest
         * @description `PATCH /auth/password` — el usuario ya está logueado, pero igual tiene
         *     que reprobar identidad con la contraseña actual (si alguien le roba la
         *     sesión, no puede usarla para expulsarlo cambiándole la contraseña).
         */
        CambiarPasswordRequest: {
            /**
             * Password Actual
             * @example secreta123
             */
            password_actual: string;
            /**
             * Password Nueva
             * @description Contraseña nueva (mínimo 8 caracteres, al menos una letra y un número)
             * @example nuevaSecreta123
             */
            password_nueva: string;
        };
        /** CarreraCreate */
        CarreraCreate: {
            /** Nombre */
            nombre: string;
            /** Duracion Cuatrimestres */
            duracion_cuatrimestres: number;
            /** Ifts Id */
            ifts_id: number;
        };
        /** CarreraResponse */
        CarreraResponse: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Duracion Cuatrimestres */
            duracion_cuatrimestres: number;
            /** Ifts Id */
            ifts_id: number;
        };
        /** CarreraUpdate */
        CarreraUpdate: {
            /** Nombre */
            nombre?: string | null;
            /** Duracion Cuatrimestres */
            duracion_cuatrimestres?: number | null;
        };
        /** ConvenioCreate */
        ConvenioCreate: {
            /** Institucion */
            institucion: string;
            /** Carrera Destino */
            carrera_destino: string;
            /** Descripcion */
            descripcion: string;
            /**
             * Link Info
             * Format: uri
             */
            link_info: string;
            /** Carrera Id */
            carrera_id: number;
        };
        /** ConvenioResponse */
        ConvenioResponse: {
            /** Institucion */
            institucion: string;
            /** Carrera Destino */
            carrera_destino: string;
            /** Descripcion */
            descripcion: string;
            /**
             * Link Info
             * Format: uri
             */
            link_info: string;
            /** Carrera Id */
            carrera_id: number;
            /** Id */
            id: number;
        };
        /** CorrelativaCreate */
        CorrelativaCreate: {
            /**
             * Materia Id
             * @description Materia que exige la correlativa
             * @example 5
             */
            materia_id: number;
            /**
             * Requiere Id
             * @description Materia que hay que tener aprobada/cursada para poder cursar `materia_id`
             * @example 2
             */
            requiere_id: number;
        };
        /** CorrelativaResponse */
        CorrelativaResponse: {
            /** Id */
            id: number;
            /** Materia Id */
            materia_id: number;
            /** Requiere Id */
            requiere_id: number;
            requiere?: components["schemas"]["MateriaResponse"] | null;
        };
        /**
         * ForgotPasswordRequest
         * @description `POST /auth/forgot-password` — dispara el envío del email de reset.
         */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             * @example ada@ifts.edu.ar
             */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MateriaCreate */
        MateriaCreate: {
            /** Carrera Id */
            carrera_id: number;
            /** Nombre */
            nombre: string;
            /** Codigo */
            codigo: string;
            /** Anio */
            anio: number;
            /** Cuatrimestre */
            cuatrimestre: number;
        };
        /** MateriaResponse */
        MateriaResponse: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Codigo */
            codigo: string;
            /** Carrera Id */
            carrera_id: number;
            /** Anio */
            anio: number;
            /** Cuatrimestre */
            cuatrimestre: number;
        };
        /** MateriaUpdate */
        MateriaUpdate: {
            /** Nombre */
            nombre?: string | null;
            /** Codigo */
            codigo?: string | null;
            /** Anio */
            anio?: number | null;
            /** Cuatrimestre */
            cuatrimestre?: number | null;
        };
        /** MateriaUsuarioCreate */
        MateriaUsuarioCreate: {
            /**
             * Materia Id
             * @example 1
             */
            materia_id: number;
            /**
             * Cursando
             * @default false
             * @example true
             */
            cursando: boolean;
            /**
             * Nota Parcial 1
             * @example 8
             */
            nota_parcial_1?: number | null;
            /**
             * Nota Parcial 2
             * @example 7
             */
            nota_parcial_2?: number | null;
            /**
             * Examen Final
             * @description Nota del examen final rendido. No aplica si promocionó (parciales >= 7): en ese caso se ignora.
             * @example null
             */
            examen_final?: number | null;
        };
        /** MateriaUsuarioResponse */
        MateriaUsuarioResponse: {
            /** Id */
            id: number;
            /** Usuario Id */
            usuario_id: number;
            /** Materia Id */
            materia_id: number;
            /** Cursando */
            cursando: boolean;
            /** Estado */
            estado: string;
            /** Nota Parcial 1 */
            nota_parcial_1: number | null;
            /** Nota Parcial 2 */
            nota_parcial_2: number | null;
            /** Examen Final */
            examen_final: number | null;
            /**
             * Nota Final
             * @description Nota que cierra la cursada: promedio de los parciales si promocionó, o el examen_final rendido si no. Es un valor calculado, no se manda en el request.
             */
            nota_final: number | null;
        };
        /** MateriaUsuarioUpdate */
        MateriaUsuarioUpdate: {
            /** Cursando */
            cursando?: boolean | null;
            /** Nota Parcial 1 */
            nota_parcial_1?: number | null;
            /** Nota Parcial 2 */
            nota_parcial_2?: number | null;
            /** Examen Final */
            examen_final?: number | null;
        };
        /**
         * MensajeResponse
         * @description Respuesta genérica de un solo mensaje (forgot/reset password).
         */
        MensajeResponse: {
            /** Detail */
            detail: string;
        };
        /** PaginatedResponse[CarreraResponse] */
        PaginatedResponse_CarreraResponse_: {
            /** Items */
            items: components["schemas"]["CarreraResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PaginatedResponse[ConvenioResponse] */
        PaginatedResponse_ConvenioResponse_: {
            /** Items */
            items: components["schemas"]["ConvenioResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PaginatedResponse[CorrelativaResponse] */
        PaginatedResponse_CorrelativaResponse_: {
            /** Items */
            items: components["schemas"]["CorrelativaResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PaginatedResponse[MateriaResponse] */
        PaginatedResponse_MateriaResponse_: {
            /** Items */
            items: components["schemas"]["MateriaResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PaginatedResponse[MateriaUsuarioResponse] */
        PaginatedResponse_MateriaUsuarioResponse_: {
            /** Items */
            items: components["schemas"]["MateriaUsuarioResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PaginatedResponse[RecordatorioResponse] */
        PaginatedResponse_RecordatorioResponse_: {
            /** Items */
            items: components["schemas"]["RecordatorioResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PaginatedResponse[RecursoResponse] */
        PaginatedResponse_RecursoResponse_: {
            /** Items */
            items: components["schemas"]["RecursoResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PaginatedResponse[TalentoTechResponse] */
        PaginatedResponse_TalentoTechResponse_: {
            /** Items */
            items: components["schemas"]["TalentoTechResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * PerfilUpdate
         * @description `PATCH /auth/me` — el alumno sólo edita su propio nombre y apellido.
         *
         *     La carrera se muestra en el perfil pero no se cambia desde acá. El email
         *     identifica la cuenta y el rol nunca se acepta desde el request. Cualquier
         *     otro campo del body se ignora.
         */
        PerfilUpdate: {
            /**
             * Nombre
             * @example Ada
             */
            nombre?: string | null;
            /**
             * Apellido
             * @example Lovelace
             */
            apellido?: string | null;
        };
        /** PromedioResponse */
        PromedioResponse: {
            /** Promedio */
            promedio: number | null;
            /** Materias Computadas */
            materias_computadas: number;
        };
        /** RecordatorioCreate */
        RecordatorioCreate: {
            /**
             * Titulo
             * @example Parcial de Programación I
             */
            titulo: string;
            /**
             * Fecha
             * Format: date-time
             * @description Datetime ISO 8601, tiene que ser futura
             * @example 2026-12-15T10:00:00
             */
            fecha: string;
            /**
             * Tipo
             * @description Libre; convención: "parcial", "tp", "final", "otro"
             * @example parcial
             */
            tipo: string;
            /**
             * Materia Id
             * @example 1
             */
            materia_id?: number | null;
        };
        /** RecordatorioResponse */
        RecordatorioResponse: {
            /** Id */
            id: number;
            /** Titulo */
            titulo: string;
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
            /** Tipo */
            tipo: string;
            /** Usuario Id */
            usuario_id: number;
            /** Materia Id */
            materia_id: number | null;
        };
        /**
         * RecordatorioUpdate
         * @description PATCH /recordatorios/{id} — edición parcial de un recordatorio propio.
         *
         *     Todos los campos son opcionales; sólo se actualizan los que llegan en el
         *     body. Las mismas validaciones que en la creación aplican cuando el campo
         *     viene presente.
         */
        RecordatorioUpdate: {
            /**
             * Titulo
             * @example Parcial de Programación I
             */
            titulo?: string | null;
            /**
             * Fecha
             * @description Datetime ISO 8601, tiene que ser futura
             * @example 2026-12-15T10:00:00
             */
            fecha?: string | null;
            /**
             * Tipo
             * @example parcial
             */
            tipo?: string | null;
            /**
             * Materia Id
             * @example 1
             */
            materia_id?: number | null;
        };
        /** RecursoCreate */
        RecursoCreate: {
            /** Titulo */
            titulo: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Descripcion */
            descripcion: string;
            /** Tipo */
            tipo?: string | null;
            /** Materia Id */
            materia_id: number;
        };
        /** RecursoResponse */
        RecursoResponse: {
            /** Titulo */
            titulo: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Descripcion */
            descripcion: string;
            /** Tipo */
            tipo?: string | null;
            /** Materia Id */
            materia_id: number;
            /** Id */
            id: number;
            /** Usuario Id */
            usuario_id: number;
            /**
             * Fecha Creacion
             * Format: date-time
             */
            fecha_creacion: string;
        };
        /**
         * ResetPasswordRequest
         * @description `POST /auth/reset-password` — token recibido por email + contraseña nueva.
         *
         *     Misma validación de contraseña que `UsuarioCreate`.
         */
        ResetPasswordRequest: {
            /**
             * Token
             * @example b8f2b3b7c1a94e6c9d0e...
             */
            token: string;
            /**
             * Password
             * @description Contraseña nueva (mínimo 8 caracteres, al menos una letra y un número)
             * @example nuevaSecreta123
             */
            password: string;
        };
        /**
         * RolUsuario
         * @enum {string}
         */
        RolUsuario: "estudiante" | "admin";
        /** TalentoTechCreate */
        TalentoTechCreate: {
            /** Carrera Id */
            carrera_id: number;
            /** Nombre Curso */
            nombre_curso: string;
            /** Categoria */
            categoria: string;
            /** Descripcion */
            descripcion: string;
            /** Duracion */
            duracion: string;
            /**
             * Link Inscripcion
             * Format: uri
             */
            link_inscripcion: string;
        };
        /** TalentoTechResponse */
        TalentoTechResponse: {
            /** Carrera Id */
            carrera_id: number;
            /** Nombre Curso */
            nombre_curso: string;
            /** Categoria */
            categoria: string;
            /** Descripcion */
            descripcion: string;
            /** Duracion */
            duracion: string;
            /**
             * Link Inscripcion
             * Format: uri
             */
            link_inscripcion: string;
            /** Id */
            id: number;
        };
        /**
         * TokenResponse
         * @description Respuesta del endpoint de login.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            usuario?: components["schemas"]["UsuarioResponse"] | null;
        };
        /**
         * UsuarioCreate
         * @description Datos necesarios para registrar un nuevo usuario.
         *
         *     Nota de seguridad: el rol NO se acepta desde el request. El registro
         *     público siempre crea usuarios con rol `estudiante`; los administradores
         *     se crean por seed o promoción manual en la base de datos.
         */
        UsuarioCreate: {
            /**
             * Nombre
             * @description Nombre
             * @example Ada
             */
            nombre: string;
            /**
             * Apellido
             * @description Apellido
             * @example Lovelace
             */
            apellido: string;
            /**
             * Email
             * Format: email
             * @description Correo electrónico único
             * @example ada@ifts.edu.ar
             */
            email: string;
            /**
             * Password
             * @description Contraseña en texto plano (mínimo 8 caracteres, al menos una letra y un número)
             * @example secreta123
             */
            password: string;
            /**
             * Carrera Id
             * @description ID de la carrera a la que pertenece
             * @example 1
             */
            carrera_id: number;
        };
        /**
         * UsuarioLogin
         * @description Datos necesarios para iniciar sesión.
         */
        UsuarioLogin: {
            /**
             * Email
             * Format: email
             * @example ada@ifts.edu.ar
             */
            email: string;
            /**
             * Password
             * @example secreta123
             */
            password: string;
        };
        /**
         * UsuarioResponse
         * @description Datos del usuario que se devuelven al frontend (sin password_hash).
         */
        UsuarioResponse: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Apellido */
            apellido: string;
            /** Email */
            email: string;
            /** Carrera Id */
            carrera_id: number;
            /**
             * Fecha Registro
             * Format: date-time
             */
            fecha_registro: string;
            rol: components["schemas"]["RolUsuario"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerifyResponse
         * @description Respuesta de `GET /auth/verify`.
         */
        VerifyResponse: {
            /** Valid */
            valid: boolean;
            /** User Id */
            user_id: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_recordatorios_recordatorios__get: {
        parameters: {
            query?: {
                tipo?: string | null;
                desde?: string | null;
                hasta?: string | null;
                materia_id?: number | null;
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Elementos por página (máx. 100) */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_RecordatorioResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recordatorio_recordatorios__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordatorioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordatorioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recordatorio_recordatorios__recordatorio_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordatorio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_recordatorio_recordatorios__recordatorio_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordatorio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordatorioUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordatorioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_carreras_materias_carreras_get: {
        parameters: {
            query?: {
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Elementos por página (máx. 100) */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_CarreraResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_carrera_materias_carreras_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarreraCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarreraResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_carrera_materias_carreras__carrera_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carrera_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarreraResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_carrera_materias_carreras__carrera_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carrera_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarreraUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarreraResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_carrera_materias_carreras__carrera_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carrera_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_materias_by_carrera_materias_carrera__carrera_id__get: {
        parameters: {
            query?: {
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Elementos por página (máx. 100) */
                per_page?: number;
            };
            header?: never;
            path: {
                carrera_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_MateriaResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_materias_materias_buscar_get: {
        parameters: {
            query: {
                q: string;
                anio?: number | null;
                cuatrimestre?: number | null;
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Elementos por página (máx. 100) */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_MateriaResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_correlativas_materias_correlativas__materia_id__get: {
        parameters: {
            query?: {
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Elementos por página (máx. 100) */
                per_page?: number;
            };
            header?: never;
            path: {
                materia_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_CorrelativaResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_correlativa_materias_correlativas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrelativaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelativaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_correlativa_materias_correlativas__correlativa_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                correlativa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_materias_usuario_materias_usuario__usuario_id__get: {
        parameters: {
            query?: {
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Elementos por página (máx. 100) */
                per_page?: number;
            };
            header?: never;
            path: {
                usuario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_MateriaUsuarioResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_promedio_materias_promedio__usuario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromedioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_materia_usuario_materias_usuario_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MateriaUsuarioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MateriaUsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_materia_usuario_materias_cursada__materia_usuario_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                materia_usuario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_materia_usuario_materias_cursada__materia_usuario_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                materia_usuario_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MateriaUsuarioUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MateriaUsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_materia_materias__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MateriaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MateriaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_materia_materias__materia_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                materia_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MateriaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_materia_materias__materia_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                materia_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MateriaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MateriaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_materia_materias__materia_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                materia_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_by_usuario_recursos_usuario__usuario_id__get: {
        parameters: {
            query?: {
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Elementos por página (máx. 100) */
                per_page?: number;
            };
            header?: never;
            path: {
                usuario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_RecursoResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_by_materia_recursos_materia__materia_id__get: {
        parameters: {
            query?: {
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Elementos por página (máx. 100) */
                per_page?: number;
            };
            header?: never;
            path: {
                materia_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_RecursoResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_by_id_recursos__recurso_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recurso_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecursoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_recursos__recurso_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recurso_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecursoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecursoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recursos__recurso_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recurso_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_recursos__get: {
        parameters: {
            query?: {
                materia_id?: number | null;
                tipo?: string | null;
                desde?: string | null;
                hasta?: string | null;
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Elementos por página (máx. 100) */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_RecursoResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recursos__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecursoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecursoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_by_carrera_convenios_carrera__carrera_id__get: {
        parameters: {
            query?: {
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Elementos por página (máx. 100) */
                per_page?: number;
            };
            header?: never;
            path: {
                carrera_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ConvenioResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_by_id_convenios__convenio_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                convenio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvenioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_convenios__convenio_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                convenio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConvenioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvenioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_convenios__convenio_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                convenio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_convenios__get: {
        parameters: {
            query?: {
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Elementos por página (máx. 100) */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ConvenioResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_convenios__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConvenioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvenioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_by_carrera_talentotech_carrera__carrera_id__get: {
        parameters: {
            query?: {
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Elementos por página (máx. 100) */
                per_page?: number;
            };
            header?: never;
            path: {
                carrera_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_TalentoTechResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_by_categoria_talentotech_categoria__categoria__get: {
        parameters: {
            query?: {
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Elementos por página (máx. 100) */
                per_page?: number;
            };
            header?: never;
            path: {
                categoria: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_TalentoTechResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_by_id_talentotech__talentotech_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                talentotech_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TalentoTechResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_talentotech__talentotech_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                talentotech_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TalentoTechCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TalentoTechResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_talentotech__talentotech_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                talentotech_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_talentotech__get: {
        parameters: {
            query?: {
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Elementos por página (máx. 100) */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_TalentoTechResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_talentotech__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TalentoTechCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TalentoTechResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_registro_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
        };
    };
    update_me_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PerfilUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_token_auth_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResponse"];
                };
            };
        };
    };
    forgot_password_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensajeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensajeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cambiar_password_auth_password_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambiarPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensajeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
